apiVersion: v1
kind: Service
metadata:
  name: airflow-dashboard
  namespace: airflow
spec:
  selector:
    component: webserver
    release: airflow
    tier: airflow
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
